### ISSUE TITLE
Bug: I Can't Turn Off or On Anything In The Green Button Menu

### ISSUE THREAD

**Issue by Adamdimoo** [webosbrew/youtube-webos#200] opened 2024-09-17 19:17 UTC
Please Help i Want To Turn Off Sponsor block

**Comment by marianmargraf** [comment] 2024-10-16 14:30
+1 on my OLED B7 55

06.10.30
webOS 3.9.2

This issue started at the same time as the other YouTube issue (dark background during playback when UI overlays are toggled)

**Comment by jospezial** [comment] 2024-11-25 04:01
@throwaway96 Switches not fixed with https://github.com/webosbrew/youtube-webos/releases/tag/v0.3.5-rc1

**Comment by fire332** [comment] 2024-12-23 12:29
Possible duplicate of #157.

**Comment by fire332** [comment] 2024-12-25 08:23
I can't reproduce this on my C1. Can anybody try out v0.3.5-rc2 and see if it's fixed?

**Comment by Informatic** [comment] 2024-12-25 08:51
Just checked v0.3.5-rc.2 on webOS 3.8.0 and seems like we have two issues:
1. On menu open no option is focused and it seems like we need to press up/down a couple of times. I think it would make sense to put focus on first checkbox on options menu open.
2. Enter handling doesn't work because on older chrome `evt.isTrusted` is always undefined :/ I am not entirely sure of the reasoning behind the check there - is `isTrusted` set to false on events coming from magic remote cursor? IMO if that's what we want to avoid, we should probably listen to this: https://webostv.developer.lge.com/develop/guides/system-ui-visibility#visibility-of-the-cursor (or alternatively, if that doesn't work for whatever reason - keep a flag that disables OK handling that's  turned on in `mousemove` and disabled in any other key press)

**Comment by fire332** [comment] 2024-12-25 09:23
Thanks for the info. I've just added a log right before the `isTrusted` check and it is only fired once. I'm thinking Youtube changed their ways between then and now.

**Comment by fire332** [comment] 2024-12-25 09:30
@throwaway96 this check was added in #143. Do you still remember which version(s) of webOS was this check required for? Or should I just remove it since it seems like it's not necessary anymore from my brief testing on my LG C1?

**Comment by fire332** [comment] 2024-12-25 09:37
Also, here's the difference between toggling a checkbox with the enter button (no pointer) vs using the pointer:

![without pointer](https://github.com/user-attachments/assets/271f5759-76c5-4df4-94db-6b802da5be80)
![with pointer](https://github.com/user-attachments/assets/1decb48d-f64c-431a-a685-35178066f437)

I find it interesting how the checkbox is toggled even though `isTrusted` is `false`.

**Comment by fire332** [comment] 2024-12-25 09:41
I'm thinking I replace the `isTrusted` check with `evt instanceof KeyboardEvent`.

**Comment by fire332** [comment] 2024-12-25 10:08
Can someone check if the PR fixes their issue on webOS 6.10 as mentioned in #241?

**Comment by Informatic** [comment] 2024-12-25 10:13
Firmware 06.10.50 is webOS 3.9.3-63013 (on W17{P,R,M}), so matches what we have here.

**Comment by fire332** [comment] 2024-12-25 10:15
Oh, good to know. I thought that version number referred to something else. I'll merge the fix now.

**Comment by Informatic** [comment] 2024-12-25 10:16
I'll check this in a minute on my TV.

**Closed** 2024-12-25 10:15 UTC
Labels: bug, question

**Comment by Informatic** [comment] 2024-12-25 10:29
Works perfectly, thanks!
