### ISSUE TITLE
Speed button

### ISSUE THREAD

**Issue by timur-79** [webosbrew/youtube-webos#65] opened 2022-12-03 04:22 UTC
No more ability to select the playback speed in the settings, it's disappeared. LG TV

**Comment by malloy139** [comment] 2022-12-12 20:23
Same here

**Comment by Informatic** [comment] 2022-12-12 20:25
Known issue, unfixable on our side due to webOS limitations. Duplicate of #6, #39 and #52 - look there for some further technical explanation.

**Closed by Informatic** 2022-12-12 20:25 UTC
