### ISSUE TITLE
Green button not working in release 0.3.4 on WebOS 2.x

### ISSUE THREAD

**Issue by VladimirZalmanek** [webosbrew/youtube-webos#169] opened 2024-04-30 06:07 UTC
The GREEN button to manage sponsor block settings does not work in app release 0.3.4 on WebOS 2.x (2.2.3-2155).
Is there another way to open this setting?

**Comment by throwaway96** [comment] 2024-04-30 23:26
No OTAID provided; duplicate of https://github.com/webosbrew/youtube-webos/issues/160. There's a link to an IPK for webOS 1/2 in the comments on that issue.

**Closed by throwaway96** 2024-04-30 23:26 UTC
Labels: duplicate
