### ISSUE TITLE
Error to Update and advertising

### ISSUE THREAD

**Issue by MPJ1988** [webosbrew/youtube-webos#158] opened 2024-04-09 06:39 UTC
Hello, since today I have been having problems with advertising being displayed. An update is not possible, I always get the message: an error occurred urgent installation: request to https:// (and then the link to Github)
![20240409_083922](https://github.com/webosbrew/youtube-webos/assets/93980800/ba705004-0536-4366-a77f-e79fa7cd2c52)

**Comment by LexxxyT** [comment] 2024-04-09 08:23
Same thing here. Updated webos Dev manager and uninstalled the app from the TV then used the manager to load the app again and still getting ads

**Comment by wiz0u** [comment] 2024-04-09 11:09
Yup ads are back :('

**Comment by mrmuiz** [comment] 2024-04-09 11:42
Same  here. Went back to  0.3.2 installed with webOS Dev Manager. And it works fine again.

**Comment by wiz0u** [comment] 2024-04-09 11:45
> Installed 0.3.2 with webOS Dev Manager. And it works fine again

Weird. I'm still on 0.3.2 and get ads.

**Comment by throwaway96** [comment] 2024-04-09 11:46
@mrmuiz

What webOS version do you have?

@wiz0u

What YTAF and webOS versions are you talking about?

Closing as duplicate of webosbrew/webos-homebrew-channel#179.

**Closed by throwaway96** 2024-04-09 11:46 UTC

**Comment by wiz0u** [comment] 2024-04-09 11:49
webOS 4.4.0
![image](https://github.com/webosbrew/youtube-webos/assets/11647984/7dac14d4-bc35-4b65-b0a3-7ccc98556ff0)
According to webOS Dev Manager, I'm still on 0.3.2. There is an update for 0.3.3 which I didn't install yet.
![image](https://github.com/webosbrew/youtube-webos/assets/11647984/74264b6b-bfaf-4820-b672-dfed4f19a883)

**Comment by mrmuiz** [comment] 2024-04-09 11:55
This one  only works with 0.3.2 or before.
![afbeelding](https://github.com/webosbrew/youtube-webos/assets/118138382/09674de8-0be0-4bcf-b90d-12b6128bf28b)


This one with all  versions ( Not rooted )
![afbeelding](https://github.com/webosbrew/youtube-webos/assets/118138382/db840957-feeb-4bd7-81ce-9e3fb5fb01b0)

**Comment by LexxxyT** [comment] 2024-04-09 12:04
Weird..... my TV says firmware is 5.70. Checked for updates and " no updates found"

**Comment by throwaway96** [comment] 2024-04-09 12:04
@mrmuiz 

Wow, I'm surprised it worked at all on webOS 1. I don't know if we (should) officially support that. I'll have to look into whether maintaining WebKit support will hold back anything else.

I may be able to release a webOS 1/2-specific version based on 0.3.2 with some of the updates from 0.3.3.

**Comment by throwaway96** [comment] 2024-04-09 12:06
@LexxxyT

Firmware version is not the same thing as webOS version. Also, if you want to be able to root your TV in the future, don't update the firmware.

**Comment by LexxxyT** [comment] 2024-04-09 12:11
Ok so I'm not sure how to get 6.4.0 unrooted version. My webos dev manager says webos 3.4.0

**Comment by mrmuiz** [comment] 2024-04-09 12:12
> 1. I

Apps install work fine on  old WEBOS. Only root does not. But thats oke. Only newer youtube versions dont work anymore now.

**Comment by throwaway96** [comment] 2024-04-09 12:13
@LexxxyT

You can't update to new webOS major versions.

**Comment by mrmuiz** [comment] 2024-04-09 12:13
> Ok so I'm not sure how to get 6.4.0 unrooted version. My webos dev manager says webos 3.4.0

Depents on  tv model/year

**Comment by mrmuiz** [comment] 2024-04-09 12:15
> @mrmuiz
> 
> Wow, I'm surprised it worked at all on webOS 1. I don't know if we (should) officially support that. I'll have to look into whether maintaining WebKit support will hold back anything else.
> 
> I may be able to release a webOS 1/2-specific version based on 0.3.2 with some of the updates from 0.3.3.

Apps install work fine on old WEBOS. Only root does not. But thats oke. Only newer youtube versions dont work anymore now.

**Comment by LexxxyT** [comment] 2024-04-09 12:15
> @wiz0u
> 
> Try the 0.3.4 release candidate from the releases page.

Perfect! and the green button settings are working again. Cheers!

**Comment by wiz0u** [comment] 2024-04-09 14:51
> @wiz0u
> 
> Try the 0.3.4 release candidate from the releases page.

I updated to 0.3.3 and it seemed enough for now. I will remember to try 0.3.4 if ads appear again.

**Comment by fergardi** [comment] 2024-04-13 11:10
I am having issues with 0.3.3, was working fine until a couple days ago. I cannot update it, gives certificate errors. Cannot use dev-manager either, using Mac M1. Last resort to install 0.3.4-rc1 is using CLI, I assume?

**Comment by mrmuiz** [comment] 2024-04-13 13:25
> I am having issues with 0.3.3, was working fine until a couple days ago. I cannot update it, gives certificate errors. Cannot use dev-manager either, using Mac M1. Last resort to install 0.3.4-rc1 is using CLI, I assume?

Uninstall youtube adfree from the  tv self. Then try again. (I had to reset my tv to defaults to get it running again. I had no root anyway.)
