### ISSUE TITLE
BUG: Still getting ads and menu not showing when using green button

### ISSUE THREAD

**Issue by yuri2o1o** [webosbrew/youtube-webos#163] opened 2024-04-14 15:59 UTC
I've used this for a few weeks and it was great, then my developer mode extension  time completed and uninstalled everything. I then re-enabled it and re-installed this and am now getting ads. I'm also unable to open the options menu (click on green button does nothing).

**Comment by delboydell** [comment] 2024-04-14 18:37
+1 here for unable to get into menu with the green button, adds showing

**Comment by scottini** [comment] 2024-04-14 19:48
same here

**Comment by rmadeira147** [comment] 2024-04-14 20:00
Have you tried using version 0.3.4?

**Comment by scottini** [comment] 2024-04-14 20:07
> Have you tried using version 0.3.4?

If you mean 0.3.4-rc1, I tried it and it doesn't work: there is no menu with the green button and ads appear.
My WebOS the 2.2.0

**Comment by rmadeira147** [comment] 2024-04-14 20:11
Try this one:

https://github.com/webosbrew/youtube-webos/releases/download/v0.3.4-rc1/youtube.leanback.v4_0.3.4_all.ipk

**Comment by throwaway96** [comment] 2024-04-14 20:13
Closing as a duplicate of #160. If anyone provides any actual information to the contrary, I'll reopen.

**Closed by throwaway96** 2024-04-14 20:13 UTC

**Comment by retroNUC** [comment] 2024-04-14 20:14
Was seeing the same issue on v0.3.3 after updating a few days ago - Was seeing preroll and interstitial ads, and the green button wasn't doing anything.

Just updated to v0.3.4-rc1, and it seems to be working again? Fingers crossed. Thanks for picking development back up, by the way.

LG OLED B7, webOS 3.5

**Comment by scottini** [comment] 2024-04-14 20:17
> Try this one:
> 
> https://github.com/webosbrew/youtube-webos/releases/download/v0.3.4-rc1/youtube.leanback.v4_0.3.4_all.ipk

Tried, no luck

**Comment by throwaway96** [comment] 2024-04-14 20:27
@scottini

See #160.

**Comment by scottini** [comment] 2024-04-14 20:29
> @scottini
> 
> See #160.

Thanks, I'll subscribe

**Comment by mhamzas** [comment] 2024-05-02 08:02
Same
