### ISSUE TITLE
Bug: video disappears when scrubbing

### ISSUE THREAD

**Issue by byertsy** [webosbrew/youtube-webos#209] opened 2024-10-21 18:47 UTC
- YTAF version: 0.3.4

## TV information

- webOS version: 9.2.0-1801
- Model: OLED77C45LA

## Issue description

When playing a video the video will disappear when I access the player menu, leaving a black screen.

**Comment by shaggybyte** [comment] 2024-10-21 19:19
I have the same issue for a week.

**Comment by cremor** [comment] 2024-10-22 14:50
Duplicate of #203
Already fixed in v0.3.5-rc1

**Closed** 2024-10-24 05:46 UTC
Labels: bug
