### ISSUE TITLE
Bug: Short video don't have image just sound

### ISSUE THREAD

**Issue by 5R5R5** [webosbrew/youtube-webos#219] opened 2024-10-29 00:08 UTC
YTAF 0.3.4
webos : 06.10.50

Hello not a big deal but I see there is a 0.3.5 version that will be certainly release soon. Since some weeks (that was not always the case), the youtube short video have no image only a black screen and the sound. I'm not really into short video but I prefer to say it if it can help for the futur update.

**Comment by cremor** [comment] 2024-10-29 06:54
Duplicate of #210

**Comment by fire332** [comment] 2024-12-23 12:19
Closing in favor of #210

**Closed by fire332** 2024-12-23 12:19 UTC
Labels: bug, duplicate
