### ISSUE TITLE
The Sponsor Block not working in release 0.3.4 on WebOS 2.x

### ISSUE THREAD

**Issue by VladimirZalmanek** [webosbrew/youtube-webos#170] opened 2024-04-30 06:10 UTC
The Sponsor Block feature does not work (ads are displayed) in app release 0.3.4 on webOS 2.x (2.2.3-2155).

**Comment by throwaway96** [comment] 2024-04-30 23:24
You didn't provide OTAID. Duplicate of #160 anyway though.

**Closed by throwaway96** 2024-04-30 23:24 UTC
Labels: bug
