### ISSUE TITLE
No progress tracking

### ISSUE THREAD

**Issue by DMoogle** [webosbrew/youtube-webos#4] opened 2021-12-05 17:29 UTC
When a video has been partially or fully watched, YouTube only recognizes that the video was started, but will not recognize how much has been watched.

E.g. if 5 minutes of a 10 minute video is watched, then a user exits the video and enters it again, the video will start from the beginning instead of at the 5 minute mark.

**Comment by Informatic** [comment] 2021-12-07 18:38
This is likely caused by overeager adblocking regex inherited from original project:
https://github.com/webosbrew/youtube-webos/blob/main/src/adblock.js#L4-L5

Can you test if this still happens with adblocking disabled?

**Comment by Informatic** [comment] 2021-12-13 18:25
Seemingly this is an issue with youtube-tv itself? https://github.com/FriedChickenButt/youtube-webos/issues/24

We could *try* reimplementing that, but that sounds like a lot of work :/

**Comment by Informatic** [comment] 2021-12-14 22:17
Have you tried disabling adblocking? I just noticed we block `www.youtube.com/ptracking` call which prevents further `watchtime` reporting.

After disabling adblocking here watchtime is properly reported here, but it doesn't seem to be respected when relaunching a video in YouTube TV.

When opening the same video in a normal browser with the same Google account logged in starts from the last watched timestamp.

**Comment by Informatic** [comment] 2021-12-20 17:36
Oh. I just realized this now works, as long as adblocking is disabled. We can fix up that URL blocking rule.

**Comment by DMoogle** [comment] 2021-12-20 17:41
Thanks man. Meant to reply earlier - how do you disable the adblocking? I
couldn't find any settings for it.

**Comment by Informatic** [comment] 2021-12-20 17:42
Press "green" button on the remote, then uncheck "Enable AdBlocking", then press "green" again, then restart the app. (since sometimes progress tracking stays disabled if a first request is blocked, it seems...)

**Comment by Informatic** [comment] 2021-12-20 17:44
You can download zipped `ipk` file here for testing, with removed `ptracking` rule:
https://github.com/webosbrew/youtube-webos/actions/runs/1603263259

An app can be installed directly on a TV over SSH like so:
```
luna-send -i -f luna://com.webos.appInstallService/dev/install '{"id":"app","ipkUrl":"/tmp/app.ipk","subscribe":true}'
```

**Comment by Informatic** [comment] 2021-12-21 09:39
Ping me whenever you verify it works properly, and I will cut a new public release onto homebrew channel.

**Comment by Informatic** [comment] 2021-12-23 21:16
Fix for this has been rolled out in v0.2.0, available in [Releases tab here](https://github.com/webosbrew/youtube-webos/releases/tag/v0.2.0) or downloadable directly Homebrew Channel already.

**Closed by Informatic** 2021-12-23 21:16 UTC

**Comment by Crazor** [comment] 2021-12-24 13:46
This does not appear to work for me. Videos are still shown as "10% watched" judging by the progress bar in my History

**Comment by Informatic** [comment] 2021-12-24 13:54
Hmmm... That is on version 0.2.0 released yesterday? Can you check if the
same thing happens with adblocking disabled again?

This seems to work fairly consistently on my side now. Wonder if that may
be caused by my Premium subscription...

**Comment by Crazor** [comment] 2021-12-24 14:06
I'm sorry, this must have been a fluke. I tried it with a couple videos I definitively had never watched before, and so far it seems to track the progress just fine. So this might have just been a hiccup on youtube's side with the video I re-watched right after updating.

Merry Christmas! ;)

**Comment by dryna2017** [comment] 2021-12-27 09:33
Здравствуйте такая проблема что было на старой прошивке 0.1.0, что теперь на 0.2.1 не сохраняет историю видео с того момента как закончил смотреть, на всех устройствах один аккаун и везде сохраняет можно ли это как-то исправить

**Comment by d42** [comment] 2021-12-27 09:46
здраствуй @dryna2017

если я правильно понял - ето работало в прошивке 0.1.0?

**Comment by dryna2017** [comment] 2021-12-27 09:47
Решите проблему пожалуйста с просмотром видео, что бы сохранялось с того момента где закончил смотреть

**Comment by dryna2017** [comment] 2021-12-27 09:51
27.12.2021, 12:47, "d42" ***@***.***>:
здраствуй @dryna2017
если я правильно понял - ето работало в прошивке 0.1.0?     Не работает история просмотра на v 0.2.1 не сохраняет видео на том месте где остановился смотреть, начинается сначало

**Comment by dryna2017** [comment] 2021-12-27 10:36
Hello, you can solve the problem in YouTube, the video is not saved from the moment it stopped, when you turn it on it starts from the beginning, it was on 0.1.0 and now on 0.2.1 it does not save the video. Please fix this error.

**Comment by dryna2017** [comment] 2021-12-27 13:27
The video is not saved from the place where you finished watching it, when you turn it on, everything starts from the beginning and the account on all devices saves one, but not here, please fix this problem, otherwise you will get tired of constantly rewinding it too, native YouTube from google worked without problems. Thank you if you help!!!

**Comment by dryna2017** [comment] 2021-12-28 10:22
> Извините, должно быть, это была случайность. Я попробовал это с парой видео, которые я определенно никогда не смотрел раньше, и до сих пор кажется, что он отлично отслеживает прогресс. Так что, возможно, это просто сбой на YouTube с видео, которое я пересмотрел сразу после обновления.
> 
> С Рождеством! ;)
